<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>369f77a6-e011-4931-af12-b8b67d45c26e</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Application\Application\Application.csproj" />
      <ProjectReference Include="..\..\Infrastructure\Infrastructure\Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Payment-Provider-Package.Infrastructure" Version="1.0.0" />
    </ItemGroup>

</Project>
