<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>0c264cd6-7eb0-4113-a9fe-0529f6c25d32</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CommonPaymentProvider" Version="1.0.0" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

</Project>
